version: '{build}'
os: Windows Server 2012
clone_depth: 3 
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
build_script:
  - mvn install -DskipTests=true
test_script:
  - mvn test -Dassembly.skipAssembly=true -B
cache:
  - C:\Users\appveyor\.m2
