language: java
git:
  depth: 3
matrix:
  include:
  - jdk: oraclejdk8
    env: DEPLOY=true
install: mvn install -DskipTests=true
script: mvn test -Dassembly.skipAssembly=true -B
after_success:
  - test "$DEPLOY" = true -a "$TRAVIS_PULL_REQUEST" = false 
    && mvn source:jar deploy --settings .travis-settings.xml -DskipTests=true -B
    && curl -LO --retry 3 https://raw.github.com/liveontologies/plume-lib/master/bin/trigger-travis.sh
    && sh trigger-travis.sh liveontologies docker-pinpointing-experiments $TRAVIS_ACCESS_TOKEN "Triggered by build of $TRAVIS_REPO_SLUG"
